services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - order-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  gateway-server:
    build: ./gateway-server
    container_name: api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8095:8095"
    networks:
      - order-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - discovery-server
      - postgres
    ports:
      - "8096:8096"
    networks:
      - order-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - order-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  order-backend:
    driver: bridge

volumes:
  postgres-data: